# Usamos una versión oficial y ligera de Python
FROM python:3.10-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Instalamos la librería necesaria para el gráfico
RUN pip install matplotlib

# Instalamos las librerías necesarias para el gráfico y la base de datos
RUN pip install matplotlib mysql-connector-python

# Copiamos todo el código de tu carpeta backend al contenedor
COPY backend/ /app/

# El comando que se ejecuta al encender el contenedor
CMD ["python", "main.py"]